[default]
OPENAI_API_KEY = "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"
GOOGLE_MAPS_API_KEY = "AIzaSyDitaRPHWr7jti9NbaJJY9_Sl9p2Ydm6E0"